# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm i -f
    - run: npm run build --if-present
    - name: GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: crazy-max/ghaction-github-pages@5859b4ea7efe6b470a5b19c570460eae9323aefc
      uses: crazy-max/ghaction-github-pages@v3.2.0
      with:
        # Git branch where assets will be deployed
        target_branch: 'main'
        # Build directory to deploy
        build_dir: 'dist'
        # Whether to treat build_dir as an absolute path
        # absolute_build_dir: # optional, default is false
