name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.14

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build
    - name: Simple GitHub Pages Deploy Action
      # You may pin to the exact commit or the version.
      # uses: rdarida/simple-github-pages-deploy-action@290913edc3f3978a087e0687a67a1cda044965c5
      uses: rdarida/simple-github-pages-deploy-action@v1
      with:
        # Set git config user.name
        git-user: 'djawad98'
        # Set git config user.email
        git-email: 'ghasedjavad@gmail.com'
        # Set the base folder for deploy
        # git-base-folder: # optional, default is dist
        # Set the commit message
        # commit-message: # optional, default is Simple GitHub Pages Deploy Action
        # Set the target branch for deployment
        # branch: # optional, default is gh-pages
